spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ secrets.RDS_HOST }}
    username: ${{ secrets.RDS_USERNAME }}
    password: ${{ secrets.RDS_PASSWORD }}
    hikari:
      maximum-pool-size: 20
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

#  sql.init.mode: always

  # 컨트롤러에서 프론트로 보내줄 때 null field 생략
  jackson:
    default-property-inclusion: non_null
