spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://my-rds-instance.crrni39fxkfz.ap-northeast-2.rds.amazonaws.com:3306/my_rds_name"
    username: "admin"
    password: "!ebnatural12"
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

#  sql.init.mode: always

  # 컨트롤러에서 프론트로 보내줄 때 null field 생략
  jackson:
    default-property-inclusion: non_null
